version: '3.8'
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend/laravel:/var/www/html

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend/laravel:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html/public

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_HOST=db
      - PMA_USER=phper
      - PMA_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - pma-session-store:/sessions

volumes:
  db-store:
  pma-session-store:
